# Исключаем каталоги, где исходный код не находится
exclude = [".git", "__pycache__", "build", "dist", "venv", "env", "migrations"]

# Целевая версия Python – обновляем под вашу версию (например, py312)
target-version = "py312"

# Устанавливаем длину строки в 120 символов
line-length = 120

[lint]
# Выбираем проверки: базовые, а также дополнительные (flake8-bugbear, pep8-naming, isort)
select = ["E", "F", "W", "B", "N", "I"]

# Отключаем проверки, которые конфликтуют с Black
ignore = ["E203"]

# Для файлов __init__.py отключаем проверку неиспользуемых импортов
per-file-ignores = { "__init__.py" = ["F401"] }

[format]
# Как и в случае с черным цветом, используйте двойные кавычки для строк.
quote-style = "double"
