from datetime import datetime
from typing import Any

from pydantic.dataclasses import dataclass

from .event_base import EventBase

@dataclass
class Call:
    call_id: str = ...
    call_date: datetime | None = ...
    answer_date: datetime | None = ...
    end_time: datetime | None = ...
    call_type: str | None = ...
    src_type: str | None = ...
    call_status: str | None = ...
    hangup_reason: str | None = ...
    dst_type: str | None = ...
    dst_num: str | None = ...
    dst_name: str | None = ...
    did: str | None = ...
    did_num: str | None = ...
    src_name: str | None = ...
    src_num: str | None = ...
    total_time: int | None = ...
    wait_time: int | None = ...
    talk_time: int | None = ...
    events_count: int | None = ...
    transfered_linked_to: bool = ...
    vpbx_id: int | None = ...
    events: list[EventBase] = ...

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Call": ...
